### ISSUE TITLE
Directing test output to a specific JIRA project or Xray test execution record

### ISSUE THREAD

**Issue by JamesFrancisco** [medtoure18/codeceptjs-xray-helper#5]
In a JIRA environment where we have multiple projects, how can we direct the helper to sent the test output to a specific project or even a specific test execution record?

**Comment by medtoure18** [comment]
yours xray tests have to be on cucumber types.
when you export yours tests from your existing Test Execution, the jira id of the Test Execution will be the first tag of the .feature file.
in this case, you have to set the plugin variable testsExportedFromTestExecution:true and your initial test execution will be updated
if your feature files are exported from Test Plan, you have to set testsExportedFromTestExecution:false so a new Test Execution will be created on your project.

**Comment by JamesFrancisco** [comment]
> yours xray tests have to be on cucumber types.

I see. We have to write the tests first in cucumber in jira. OK thanks
